---
- name: Configuring server
  hosts: all
  become: yes
  roles:
    - role: apt
      vars:
        apt_pkg:
          - kitty
          - nodejs
    - role: php
      vars: 
        php_version: 8.3
