---
- name: Configuring server
  hosts: all
  become: yes
  roles:
    - role: dns
    - role: incus
    - role: apt
      vars: 
        apt_pkg:
          - podman
          - netavark
          - wireguard
    - role: php
      vars: 
        php_version: 8.2
