---
- name: Adding PHP ondrej PPA repository
  ansible.builtin.apt_repository:
    repo: ppa:ondrej/php
- name: Installing mandatory packages via apt
  ansible.builtin.apt:
    pkg: 
      - "php{{ php_version }}"
      - "php{{ php_version }}-bcmath"
      - "php{{ php_version }}-bz2"
      - "php{{ php_version }}-cli"
      - "php{{ php_version }}-common"
      - "php{{ php_version }}-curl"
      - "php{{ php_version }}-gd"
      - "php{{ php_version }}-igbinary"
      - "php{{ php_version }}-intl"
      - "php{{ php_version }}-mbstring"
      - "php{{ php_version }}-mcrypt"
      - "php{{ php_version }}-mysql"
      - "php{{ php_version }}-pgsql"
      - "php{{ php_version }}-readline"
      - "php{{ php_version }}-redis"
      - "php{{ php_version }}-sqlite3"
      - "php{{ php_version }}-swoole"
      - "php{{ php_version }}-tidy"
      - "php{{ php_version }}-xdebug"
      - "php{{ php_version }}-yaml"
      - "php{{ php_version }}-zip"
