---
- name: Configuring workspace
  hosts: all
  become: yes
  roles:
    - role: dns
    - role: incus
    - role: apt
      vars: 
        repo:
          - ppa:libreoffice/ppa
        pkg:
          - podman
          - netavark
          - wireguard
          - firefox
          - telegram-desktop
          - libreoffice